#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @import rlang
#' @importFrom bs4Dash accordion
#' @importFrom bs4Dash accordionItem
#' @importFrom bs4Dash bs4Card
#' @importFrom bs4Dash navbarTab
#' @importFrom bs4Dash sortable
#' @importFrom bs4Dash tabItem
#' @importFrom bs4Dash tabItems
#' @importFrom bs4Dash tooltip
#' @importFrom bs4Dash updateNavbarTabs
#' @importFrom dplyr across
#' @importFrom dplyr add_count
#' @importFrom dplyr all_of
#' @importFrom dplyr arrange
#' @importFrom dplyr case_match
#' @importFrom dplyr case_when
#' @importFrom dplyr contains
#' @importFrom dplyr cross_join
#' @importFrom dplyr distinct
#' @importFrom dplyr distinct_all
#' @importFrom dplyr ends_with
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr inner_join
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr select
#' @importFrom dplyr slice_head
#' @importFrom dplyr starts_with
#' @importFrom dplyr ungroup
#' @importFrom flextable autofit
#' @importFrom flextable htmltools_value
#' @importFrom formatters var_labels
#' @importFrom formatters var_relabel
#' @importFrom purrr discard
#' @importFrom purrr every
#' @importFrom purrr keep
#' @importFrom purrr list_assign
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_lgl
#' @importFrom purrr modify_if
#' @importFrom purrr none
#' @importFrom purrr reduce
#' @importFrom purrr set_names
#' @importFrom purrr walk
#' @importFrom reactable colDef
#' @importFrom reactable reactable
#' @importFrom reactable reactableOutput
#' @importFrom reactable renderReactable
#' @importFrom rtables add_colcounts
#' @importFrom rtables add_overall_col
#' @importFrom rtables append_topleft
#' @importFrom rtables cbind_rtables
#' @importFrom rtables drop_split_levels
#' @importFrom rtables obj_label
#' @importFrom rtables remove_split_levels
#' @importFrom rtables split_cols_by_multivar
#' @importFrom rtables tt_to_flextable
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyjs disable
#' @importFrom shinyjs enable
#' @importFrom shinyjs hide
#' @importFrom shinyjs reset
#' @importFrom shinyjs runjs
#' @importFrom shinyjs show
#' @importFrom shinyjs toggleState
#' @importFrom shinyjs useShinyjs
#' @importFrom shinyWidgets prettyCheckboxGroup
#' @importFrom shinyWidgets prettyRadioButtons
#' @importFrom shinyWidgets prettySwitch
#' @importFrom shinyWidgets show_toast
#' @importFrom shinyWidgets updatePrettyCheckboxGroup
#' @importFrom stringr str_detect
#' @importFrom stringr str_glue
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_sub
#' @importFrom stringr str_to_title
#' @importFrom stringr str_trunc
#' @importFrom tern append_varlabels
#' @importFrom tern count_occurrences
#' @importFrom tern count_patients_with_event
#' @importFrom tern count_patients_with_flags
#' @importFrom tern count_values
#' @importFrom tern df_explicit_na
#' @importFrom tern summarize_colvars
#' @importFrom tern summarize_num_patients
#' @importFrom tibble tibble
#' @importFrom tidyr replace_na
#' @importFrom waiter spin_ball
## usethis namespace: end
NULL
