#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @import rlang
#' @importFrom dplyr add_count
#' @importFrom dplyr all_of
#' @importFrom dplyr arrange
#' @importFrom dplyr case_match
#' @importFrom dplyr case_when
#' @importFrom dplyr cross_join
#' @importFrom dplyr distinct
#' @importFrom dplyr distinct_all
#' @importFrom dplyr ends_with
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr select
#' @importFrom dplyr slice_head
#' @importFrom dplyr starts_with
#' @importFrom dplyr ungroup
#' @importFrom formatters var_labels
#' @importFrom formatters var_relabel
#' @importFrom purrr discard
#' @importFrom purrr every
#' @importFrom purrr keep
#' @importFrom purrr list_assign
#' @importFrom purrr map
#' @importFrom purrr modify_if
#' @importFrom purrr none
#' @importFrom purrr reduce
#' @importFrom purrr set_names
#' @importFrom rtables add_colcounts
#' @importFrom rtables add_overall_col
#' @importFrom rtables cbind_rtables
#' @importFrom rtables drop_split_levels
#' @importFrom rtables obj_label
#' @importFrom rtables remove_split_levels
#' @importFrom shinycssloaders withSpinner
#' @importFrom shinyWidgets show_toast
#' @importFrom stringr str_detect
#' @importFrom stringr str_glue
#' @importFrom stringr str_remove_all
#' @importFrom stringr str_to_title
#' @importFrom stringr str_trunc
#' @importFrom tern append_varlabels
#' @importFrom tern count_occurrences
#' @importFrom tern count_patients_with_event
#' @importFrom tern count_patients_with_flags
#' @importFrom tern count_values
#' @importFrom tern df_explicit_na
#' @importFrom tern summarize_num_patients
#' @importFrom tidyr replace_na
#' @importFrom waiter spin_ball
## usethis namespace: end
NULL
